Repository EasyScience/EasyCore, pull requests merged in 2022-11, with the labels that each got.

#163 Changes to allow the skip argument to actually work.
  .github/workflows/ci_pip.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/ossar-analysis.yml
  .github/workflows/python-package.yml
  .github/workflows/python-publish.yml
  .github/workflows/self_publish_alpha.yml
  easyCore/Utils/io/xml.py
  pyproject.toml
  tests/unit_tests/utils/io_tests/test_xml.py
Labels: bug

#164 Multifitter implementation
  .pre-commit-config.yaml
  easyCore/Fitting/Constraints.py
  easyCore/Fitting/Fitting.py
  easyCore/Fitting/bumps.py
  easyCore/Fitting/fitting_template.py
  easyCore/Fitting/lmfit.py
  easyCore/Utils/typing.py
  pyproject.toml
  tests/unit_tests/Fitting/test_fitting.py
Labels: feature

#142 IO serialization
  .github/workflows/ci_pip.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/ossar-analysis.yml
  .github/workflows/python-package.yml
  .github/workflows/python-publish.yml
  .github/workflows/self_publish_alpha.yml
  .pre-commit-config.yaml
  docs/src/requirements.txt
  easyCore/Fitting/Constraints.py
  easyCore/Fitting/Fitting.py
  easyCore/Fitting/bumps.py
  easyCore/Fitting/fitting_template.py
  easyCore/Fitting/lmfit.py
  easyCore/Objects/Borg.py
  easyCore/Objects/Groups.py
  easyCore/Objects/Inferface.py
  easyCore/Objects/ObjectClasses.py
  easyCore/Objects/Variable.py
  easyCore/Objects/core.py
  easyCore/Objects/virtual.py
  easyCore/REDIRECT.py
  easyCore/Utils/UndoRedo.py
  easyCore/Utils/io/dict.py
  easyCore/Utils/io/json.py
  easyCore/Utils/io/star.py
  easyCore/Utils/io/template.py
  easyCore/Utils/io/xml.py
  easyCore/Utils/json.py
  easyCore/Utils/typing.py
  easyCore/__init__.py
  examples_old/example4.py
  examples_old/example5_broken.py
  examples_old/example6_broken.py
  pyproject.toml
  requirements.txt
  tests/unit_tests/Fitting/test_fitting.py
  tests/unit_tests/Objects/test_BaseObj.py
  tests/unit_tests/Objects/test_Descriptor_Parameter.py
  tests/unit_tests/Objects/test_Groups.py
  tests/unit_tests/Objects/test_Virtual.py
  tests/unit_tests/utils/io_tests/__init__.py
  tests/unit_tests/utils/io_tests/test_core.py
  tests/unit_tests/utils/io_tests/test_dict.py
  tests/unit_tests/utils/io_tests/test_json.py
  tests/unit_tests/utils/io_tests/test_star.py
  tests/unit_tests/utils/io_tests/test_xml.py
Labels: enhancement
